spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      db1:
        url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db2:
        url: jdbc:mysql://localhost:3306/tbk?serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20